# Site settings
title: You Can Learn How To Code  
header-img: img/home-bg.png
email: julieannesays@gmail.com
copyright_name: jmcmanus1
description: > # this means to ignore newlines until "baseurl:"
  my journey to becoming a programmer at Flatiron 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jmcmanus1
learn_profile: jmcmanus1
email_username: julieannesays@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
